# ==========================
# CONFIGURACIÓN ESPECÍFICA AUDITORÍA
# Nombre de app: AUDITORIA-REGISTROS-SERVICE
# ==========================

server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://postgres-db-auditoria:5432/auditoria_db
    # Si quieres, estos se pueden sobreescribir con ENV en docker-compose
    username: ${SPRING_DATASOURCE_USERNAME:auditoria_user}
    password: ${SPRING_DATASOURCE_PASSWORD:auditoria_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: false

# ==========
# OPENAPI / SWAGGER
# ==========
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packagesToScan: com.votaciones.auditoria_registros.controller
  pathsToMatch: /**
  override-with-generic-response: false

api:
  common:
    version: 1.0.0
    title: API Auditoría y Registros - Sistema de Votaciones
    description: Microservicio para la auditoría y registro de acciones dentro del sistema de votaciones electorales.
    termsOfService: https://www.tuvotacion.com/terminos
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.tuvotacion.com/wiki
    contact:
      name: Soporte Sistema de Votaciones
      url: https://www.tuvotacion.com/contacto
      email: soporte@tuvotacion.com

  responseCodes:
    ok.description: OK
    badRequest.description: Solicitud incorrecta, formato inválido o parámetros erróneos.
    notFound.description: No encontrado, el id especificado no existe en los registros de auditoría.
    unprocessableEntity.description: Entidad no procesable, no se pueden procesar los parámetros de entrada.

  auditoriaRegistros:
    get-auditoriaRegistro:
      description: Retorna la información de un registro de auditoría según el ID proporcionado.
      notes: |
        # Respuesta exitosa
        Si el ID del registro de auditoría existe, se retorna la información correspondiente.

        # Respuestas con error
        1. Si el ID es inválido o no existe, se devuelve un error **404 - Not Found**.
      parameters:
        id: ID del registro de auditoría a consultar
    create-auditoriaRegistro:
      description: Crea un nuevo registro de auditoría.
      notes: |
        # Respuesta exitosa
        Retorna el registro de auditoría creado.

        # Respuestas con error
        1. Si los datos enviados son inválidos se devuelve un error **400 - Bad Request**
    delete-auditoriaRegistro:
      description: Elimina un registro de auditoría según el ID proporcionado.
      notes: |
        # Respuesta exitosa
        Si el ID del registro de auditoría existe, se elimina el registro.

        # Respuestas con error
        1. Si el ID no existe se devuelve un error **404 - Not Found**
        2. Si el ID enviado es inválido se devuelve un error **400 - Bad Request**
      parameters:
        id: ID del registro de auditoría a eliminar
