server:
  port: 8085

spring:
  datasource:
    # local
    #url: jdbc:postgresql://localhost:5435/auditoria_db
    # para docker luego usaremos otro yml con override
    url: jdbc:postgresql://postgres-db-auditoria:5432/auditoria_db
    username: ${SPRING_DATASOURCE_USERNAME:auditoria_user}
    password: '{cipher}d1bd2ddba20bcea349cf8262df63a18f6e84d301f497dd598e8d36800308372b'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
