server:
  port: 8086

spring:
  datasource:
    # local
    #url: jdbc:postgresql://localhost:5436/resultados_db
    # para docker luego usaremos otro yml con override
    url: jdbc:postgresql://postgres-db-resultados:5432/resultados_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: '{cipher}2bcdd83b5039b904ea8dac148549d8868ff055b180b2d796932d1446ab088bd3'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
