server:
  port: 8081
spring:
  # Sección de la Base de Datos
  datasource:
    # Para desarrollo local
    url: jdbc:postgresql://postgres-db-usuarios:5432/usuarios_db #
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    # IMPORTANTE: Para producción, encriptar la contraseña con Spring Cloud Config Encryption
    password: "{cipher}TU_PASSWORD_ENCRIPTADO_AQUI"
    # O para desarrollo local (sin encriptar):
    # password: password
    driver-class-name: org.postgresql.Driver
  # Sección de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Sección de Spring Cloud Stream (Kafka)
  cloud:
    stream:
      function:
        definition: enviarNotificacion
      bindings:
        enviarNotificacion-out-0:
          destination: topic-notificaciones
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
# Configuración de Eureka (ya está en application.yml, pero puede override)
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
# Configuración personalizada de la aplicación
app:
  auditoria:
    base-url: http://AUDITORIA-REGISTROS-SERVICE
