server:
  port: 8081

# =======================================================
# UNA ÚNICA CLAVE 'spring:' PARA TODA LA CONFIGURACIÓN
# =======================================================
spring:
  application:
    name: usuarios-service

  # Sección de la Base de Datos
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # Sección de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Sección de Spring Cloud Stream (Kafka)
  cloud:
    stream:
      function:
        definition: enviarNotificacion
      bindings:
        enviarNotificacion-out-0:
          destination: topic-notificaciones
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://host.docker.internal:8090/realms/votaciones/protocol/openid-connect/certs}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost

app:
  auditoria:
    base-url: http://AUDITORIA-REGISTROS-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"
