server:
  port: 8081

spring:
  datasource:
    # Apuntamos a la base de datos de usuarios por su nombre de servicio en Docker
    url: jdbc:postgresql://postgres-db-usuarios:5432/usuarios_db
    username: postgres
    # Dejaremos la contraseña en texto plano POR AHORA. La encriptaremos en el siguiente paso.
    password: password
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
# ... y cualquier otra configuración específica de usuarios-service
