server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/votaciones_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  cloud:
    stream:
      function:
        definition: enviarNotificacionVotacion
      bindings:
        enviarNotificacionVotacion-out-0:
          destination: topic-notificaciones
        enviarVotacionAResultados-out-0:
          destination: topic-votaciones
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://host.docker.internal:8090/realms/votaciones/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

app:
  auditoria:
    base-url: http://AUDITORIA-REGISTROS-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
