server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres-votaciones:5432/votaciones_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  cloud:
    stream:
      function:
        definition: enviarNotificacionVotacion
      bindings:
        enviarNotificacionVotacion-out-0:
          destination: topic-notificaciones
        enviarVotacionAResultados-out-0:
          destination: topic-votaciones
      kafka:
        binder:
          brokers: kafka:9092
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/votaciones/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

app:
  auditoria:
    base-url: http://AUDITORIA-REGISTROS-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: DEBUG
