server:
  port: 8082

spring:
  datasource:
    # local
    #url: jdbc:postgresql://localhost:5433/votaciones_db
    # para docker luego usaremos otro yml con override
    url: jdbc:postgresql://postgres-votaciones:5432/votaciones_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: '{cipher}3876945519a1d11fa194c7e0d4cefadb18345602602a518e20daa4e9fcab7e62'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      function:
        definition: enviarNotificacionVotacion
      bindings:
        enviarNotificacionVotacion-out-0:
          destination: topic-notificaciones
        enviarVotacionAResultados-out-0:
          destination: topic-votaciones
      kafka:
        binder:
          brokers: ${SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS:localhost:9092}

app:
  auditoria:
    base-url: http://AUDITORIA-REGISTROS-SERVICE

logging:
  level:
    org.springframework.security: DEBUG
